### ISSUE TITLE
config error

### ISSUE THREAD

**Issue by styleNie** [Avmb/lowrank-highwaynetwork#1]
Hi, I have run the code mnist_highwaylrdiagdropoutbnl2hl.py and got an error like this,
C:\Users\Administrator\Desktop\lowrank-highwaynetwork-master>python mnist_highwa
ylrdiagdropoutbnl2hl.py
Using gpu device 0: GeForce GT 630 (CNMeM is enabled with initial size: 75.0% of
 memory, CuDNN not available)
D:\soft\python\lib\site-packages\theano\tensor\signal\downsample.py:6: UserWarni
ng: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
Traceback (most recent call last):
  File "mnist_highwaylrdiagdropoutbnl2hl.py", line 43, in <module>
    model = L2HingeNeuralClassifier(input_dim=28*28, last_layer_l2_regularizatio
n = l2_reg)
  File "C:\Users\Administrator\Desktop\lowrank-highwaynetwork-master\l2hinge_cla
ssifier.py", line 17, in **init**
    super(L2HingeNeuralClassifier, self).**init**(input_dim, config=config, inpu
t_tensor=input_tensor)
TypeError: **init**() got an unexpected keyword argument 'config'

I was the first time to use deepy and not familiar with it, can you help me?
Thanks!

**Comment by Avmb** [comment]
It seems that between different versions of deepy they changed the interface. You can safely remove the config parameter.
